/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mousemover;

import java.awt.SystemTray;
import java.io.IOException;

import javax.swing.JOptionPane;

public class Main {
	public static void main(String[] args) throws IOException {
		I18NHelper.init();
		
		
		Logic logic = new Logic();
		if (!SystemTray.isSupported()) {
			JOptionPane.showMessageDialog(null, I18NHelper.getMessage("tray_not_supported_header"),
					I18NHelper.getMessage("tray_not_supported_body"), JOptionPane.ERROR_MESSAGE);
			return;
		} else {
			TrayUi tray = new TrayUi(logic);
			logic.setUi(tray);
			
		}

	}
}
